# Script generated by ChatGPT to send various packets and test wireminnow

import random
import socket
import time
from scapy.all import *

def send_random_tcp_packet():
    # Choose a random website to send TCP packet
    websites = ['google.com', 'facebook.com']
    target_website = random.choice(websites)
    target_ip = socket.gethostbyname(target_website)

    # Craft TCP packet
    source_port = random.randint(1024, 65535)
    dest_port = 80
    seq_num = random.randint(1000, 9999)
    ack_num = 0
    tcp_packet = IP(dst=target_ip)/TCP(sport=source_port, dport=dest_port, seq=seq_num, ack=ack_num, flags="S")

    # Send the packet
    send(tcp_packet)

def send_dns_request():
    # Craft DNS request
    dns_packet = IP(dst="8.8.8.8") / UDP(sport=random.randint(1024, 65535), dport=53) / DNS(rd=1, qd=DNSQR(qname="purdue.edu"))

    # Send DNS request
    send(dns_packet)

def send_miscellaneous_request():
    # Craft a miscellaneous request (e.g., ICMP)
    icmp_packet = IP(dst="8.8.8.8") / ICMP()

    # Send the packet
    send(icmp_packet)

if __name__ == "__main__":
    while True:
        send_random_tcp_packet()
        send_dns_request()
        send_miscellaneous_request()
        time.sleep(0.25)  # Adjust the interval as needed

